load("@npm//jest-cli:index.bzl", _jest_test = "jest_test")

def jest_test(
        srcs,
        deps = [],
        jest_config = "",
        data = [],
        **kwargs):
    "A macro around the autogenerated jest_test rule"
    args = [
        "--no-cache",
        "--no-watchman",
        "--ci",
        "--colors",
    ]

    args.extend(["--config", "$(rootpath %s)" % jest_config])

    for src in srcs:
        test_name = src[0:src.rindex(".")]
        _jest_test(
            name = test_name,
            data = [jest_config, src] + deps + data,
            link_workspace_root = True,
            args = args + ["--runTestsByPath", "$(rootpath %s)" % src],
            **kwargs
        )
